### ISSUE TITLE
Race-Condition in RefCounted

### ISSUE THREAD

**Issue by WanzenBug** [anlumo/cef#1]
I noticed a potential issue during the presentation at the Vienna Rust Meetup:

There is a potential race condition in the release function of the RefCounted wrapper:
https://github.com/anlumo/cef/blob/1d737f69b6b03f7f14c649f265ebd52d6eba3828/src/refcounted.rs#L242-L249

Assume there are 2 threads `B` and `B` both calling `release()`. Thread `A` runs until the strong_count is computed, but before `Drop::drop` is called on the `Arc`. The count would be non-zero, as both threads still have a reference.

Now Thread `B` runs the full function, again with a count of non-zero (`A` has not decremented yet!)

Then `A` resumes, releasing the pointed to data, while reporting that nothing was released.

Depending on what CEF does with this information there could be some issues, I haven't checked the sources. Just wanted to note that this code may not work as expected.

**Comment by Osspial** [comment]
Thanks for bringing this to our attention!

I've addressed this by replacing the `Arc`-based implementation with an `AtomicUsize`-based impl. We originally switched to `Arc` in order to take advantage of the safety auditing that's gone into the standard library, and it's unfortunate that we can't continue to use that! Anyhow, I've committed the new implementation in 81455e35b8c4a5472bda36f3d84039903045b344. The details are largely copied from the standard `Arc` so that *should* be correct, but would you be able to take a quick look at that to verify it? It's good to get multiple eyes on this sort of thing.

**Comment by WanzenBug** [comment]
Looks fine to me, the only thing missing is this memory fence on drop https://doc.rust-lang.org/src/alloc/sync.rs.html#1194

**Comment by Osspial** [comment]
Alright, I've added that in. Again, thank you for raising this issue!
